### ISSUE TITLE
Add new folder Leetcode

### ISSUE THREAD

**Issue by Gaurav8604** [Vedeesh6/Java-Codespace#285]
Add new folder for leetcode problems 
and add problems of 2Sum, 3Sum and 4Sum problems in java
Please add the hactoberfest tag.

**Comment by Gaurav8604** [comment]
Please assign me this issue

**Comment by Vedeesh6** [comment]
Here you are. Proceed with it.

**Comment by Gaurav8604** [comment]
@Vedeesh6 Can you please the hactoberfest tag??
